#cloud-config

ssh_authorized_keys:
  - ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6NF8iallvQVp22WDkTkyrtvp9eWW6A8YVr+kz4TjGYe7gHzIw+niNltGEFHzD8+v1I2YJ6oXevct1YeS0o9HZyN1Q9qgCgzUFtdOKLv6IedplqoPkcmF0aYet2PkEDo3MlTBckFXPITAMzF8dJSIFo9D8HfdOV0IAdx4O7PtixWKn5y2hMNG0zQPyUecp4pzC6kivAIhyfHilFR61RGL+GPXQ2MWZWFYbAGjyiYJnAmCP3NOTd0jMZEnDkbUvxhMmBYSdETk1rRgm+R4LOzFUGaHqHDLKLX+FIPKcF96hrucXzcWyLbIbEgE98OHlnVYCzRdK8jlqm8tehUc9c9WhQ== vagrant insecure public key

coreos:
  oem:
    id: vagrant
    name: CoreOS.box for Vagrant
    version-id: 0.8.0
    home-url: https://vagrantcloud.com/yungsang/coreos
    bug-report-url: https://github.com/YungSang/coreos-packer

  units:
    - name: coreos-cloudinit-vagrant-mkdir.service
      command: start
      runtime: yes
      content: |
        [Service]
        Type=oneshot
        ExecStart=/bin/mkdir -p /var/lib/coreos-vagrant

    - name: coreos-cloudinit-vagrant-user.path
      command: start
      runtime: no
      content: |
        [Path]
        PathExists=/var/lib/coreos-vagrant/vagrantfile-user-data

    - name: coreos-cloudinit-vagrant-user.service
      runtime: no
      content: |
        [Unit]
        ConditionFileNotEmpty=/var/lib/coreos-vagrant/vagrantfile-user-data

        [Service]
        Type=oneshot
        EnvironmentFile=/etc/environment
        ExecStart=/usr/bin/coreos-cloudinit --from-file /var/lib/coreos-vagrant/vagrantfile-user-data
        RemainAfterExit=yes

#    - name: coreos-cloudinit-vagrant-user.path
#      command: start
#      runtime: yes
#      content: |
#        [Path]
#        PathExists=/var/lib/coreos-vagrant/vagrantfile-user-data
#        Unit=user-cloudinit@var-lib-coreos\x2dvagrant-vagrantfile\x2duser\x2ddata.service

    - name: docker-tcp.socket
      command: start
      runtime: no
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=4243
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target

    - name: docker.service
      command: start
